spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: 123456
  mvc:
    view:
      prefix: /templates
      suffix: .html
    date-format: yyyy-MM-dd
  messages:
    basename: i18n/login
  thymeleaf:
    cache: false
    suffix: .html